

spring:
  datasource:
    druid:
      #最小连接池数量min-idle=3
      min-idle: 3
      #初始化时建立物理连接的个数
      initial-size: 3
      #最大连接池数量
      max-active: 10
      #获取连接时最大等待时间
      max-wait: 60000
      #配置监控页面访问登录名称
      #配置监控页面访问密码
      stat-view-servlet:
        login-username: root
        login-password: root
      #是否开启慢sql查询监控
      filter:
        stat:
          log-slow-sql: true
          #慢SQL执行时间
          slow-sql-millis: 1


server:
  port: 8104

